FORMAT: 1A
HOST: https://pymasapi.okapi.io/1.0/
# MAS API - Python wrapper class

Python wrapper for Singapore Monetary Authority (MAS) API.
API includes credit/debit card stats, exchange rates, interest rates, money supply.

## Credit Card stats [/credit_card?period=annual&limit=5]

### List Credit Card stats [GET]

+ Response 200 (application/json)

    
        {
            "help":"Search a datastore table. :param resource_id: id or alias of the data that is going to be selected.",
            "success":true,
            "result":{
            "fields":
                [{"id":"end_of_month","type":"text"},
                {"id":"preliminary","type":"text"},
                {"id":"cards_main","type":"int"},
                {"id":"cards_supp","type":"int"},
                {"id":"total_card_billings","type":"float"},
                {"id":"rollover_bal","type":"float"},
                {"id":"bad_debts_written_off","type":"float"},                                            {"id":"charge_off_rates","type":"float"}],
            "resource_id":["7f1363cc-3875-4e03-a389-fc47342bb840"],
            "limit":5,
            "total":"310",
            "records":
                [{"end_of_month":"1991-01","preliminary":"0","cards_main":"543435","cards_supp":"276974","total_card_billings":"270.4","rollover_bal":"297.1","bad_debts_written_off":"2.3","charge_off_rates":null,"feeds_flatstore_entry_id":"6591","timestamp":"1480472133","feeds_entity_id":null},
                {"end_of_month":"1991-02","preliminary":"0","cards_main":"548887","cards_supp":"281988","total_card_billings":"231.9","rollover_bal":"320.8","bad_debts_written_off":"1.3","charge_off_rates":null,"feeds_flatstore_entry_id":"6592","timestamp":"1480472133","feeds_entity_id":null},
                {"end_of_month":"1991-03","preliminary":"0","cards_main":"561003","cards_supp":"281872","total_card_billings":"229.5","rollover_bal":"311.2","bad_debts_written_off":"1.1","charge_off_rates":"6.2","feeds_flatstore_entry_id":"6593","timestamp":"1480472133","feeds_entity_id":null},
                {"end_of_month":"1991-04","preliminary":"0","cards_main":"574342","cards_supp":"286936","total_card_billings":"262.3","rollover_bal":"320.5","bad_debts_written_off":"1.1","charge_off_rates":null,"feeds_flatstore_entry_id":"6594","timestamp":"1480472133","feeds_entity_id":null},
                {"end_of_month":"1991-05","preliminary":"0","cards_main":"589765","cards_supp":"292965","total_card_billings":"277.3","rollover_bal":"324.6","bad_debts_written_off":"1.4","charge_off_rates":null,"feeds_flatstore_entry_id":"6595","timestamp":"1480472133","feeds_entity_id":null}]
        }